[package]
name = "nd-dirsum"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.99"
argh = "0.1.13"
base16ct = { version = "0.3.0", features = [ "alloc" ] }
sha2 = "0.10.9"
walkdir = "2.5.0"
